name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t justinguechi/keol-sse:latest .
    - name: Push the Docker image
      run: docker login -u justinguechi -p ${{secrets.DOCKER_HUB_KEY}}
           docker push justinguechi/keol-sse:latest
