name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login To Docker
      run: docker login -u justinguechi -p ${{secrets.DOCKER_HUB_KEY}}
    - name: Build the frontend Docker image
      run: docker build -t justinguechi/keol-sse-frontend:latest ./keol-sse-frontend
    - name: Push the frontend Docker image
      run: docker push justinguechi/keol-sse-frontend:latest
    - name: Build the backend Docker image
      run: docker build -t justinguechi/keol-sse-backend:latest ./keol-sse-back-end
    - name: Push the backend Docker image
      run: docker push justinguechi/keol-sse-backend:latest
